//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTING_MONTH
    {
        public int ACCOUNTING_MONTH_ID { get; set; }
        public Nullable<int> MONTH_NUMBER { get; set; }
        public Nullable<int> YEAR_NUMBER { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
