//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_SUPPLIER_SITE_ALL
    {
        public int VENDOR_SITE_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string VENDOR_SITE_CODE { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public Nullable<int> ORG_ID { get; set; }
    }
}
