//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_FORECAST_LINES
    {
        public decimal FORECAST_LINE_ID { get; set; }
        public Nullable<decimal> FORECAST_HEADER_ID { get; set; }
        public Nullable<decimal> FUEL_TEMPLATE_LINE_ID { get; set; }
        public Nullable<decimal> CLAIMED_VALUE { get; set; }
        public Nullable<decimal> VERIFIED_VALUE { get; set; }
        public string CHANGE_REASON { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    }
}
