//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_CDP_HEADERSYYYYYYYYYXXXX
    {
        public decimal CDP_ID { get; set; }
        public Nullable<decimal> TO_CUSTOMER_ID { get; set; }
        public Nullable<decimal> FROM_CUSTOMER_ID { get; set; }
        public string CDP_NUMBER { get; set; }
        public string GRID_STATION_CODE { get; set; }
        public string GRID_STATION_NAME { get; set; }
        public string LINE_NAME_CODE { get; set; }
        public Nullable<decimal> CONTROLLED_BY_CODE { get; set; }
        public string DISCO_AREA_CODE { get; set; }
        public string LOCATION_CODE { get; set; }
        public string LOCATION_NAME { get; set; }
        public string ENGY_IMP_EXP_FROM_CODE { get; set; }
        public string ENGY_IMP_EXP_TO_CODE { get; set; }
        public string GRID_VOLTAGE_CODE { get; set; }
        public string TF_LINE_VOLTAGE { get; set; }
        public string TF_TL { get; set; }
        public string CDP_UNIT_CODE { get; set; }
        public string FEEDER_NAME_CODE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
        public string CDP_STATUS_CODE { get; set; }
        public string REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string GROUP_COMP { get; set; }
        public Nullable<decimal> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<decimal> SR_NO_TMP { get; set; }
    }
}
