//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_CDP_DETAIL
    {
        public decimal CDP_DTL_ID { get; set; }
        public Nullable<decimal> CDP_ID { get; set; }
        public string METER_MAKE_CODE { get; set; }
        public string METER_NO { get; set; }
        public string IS_PRIMARY_METER { get; set; }
        public Nullable<decimal> MLT_FCT_ENERGY { get; set; }
        public Nullable<decimal> MLT_FCT_MDI { get; set; }
        public Nullable<decimal> MAX_RANGE { get; set; }
        public Nullable<decimal> CORRECTION_FACTOR { get; set; }
        public Nullable<decimal> INITIAL_IMPORT_READING { get; set; }
        public Nullable<decimal> INITIAL_EXPORT_READING { get; set; }
        public string METER_UNIT_CODE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
        public string REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string GROUP_COMP { get; set; }
        public Nullable<decimal> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    }
}
