//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_PPA_SCH_10_DTL
    {
        public decimal SCH_10_DTL_ID { get; set; }
        public int SCH_10_ID { get; set; }
        public decimal Ambient_Temperature { get; set; }
        public decimal NetPlant_Output { get; set; }
        public decimal Correction_Factor { get; set; }
        public Nullable<decimal> DG_Output { get; set; }
        public Nullable<decimal> STG_Output { get; set; }
        public Nullable<decimal> Equivalent_Output { get; set; }
    }
}
