//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_FORECAST_HEADER
    {
        public decimal FORECAST_HEADER_ID { get; set; }
        public Nullable<decimal> FORECAST_NO { get; set; }
        public Nullable<decimal> VENDOR_ID { get; set; }
        public Nullable<decimal> VENDOR_SITE_ID { get; set; }
        public Nullable<decimal> PPA_PLANT_EMO_ID { get; set; }
        public string BLOCK_TITLE { get; set; }
        public Nullable<decimal> PPA_PLT_BLK_FUEL_ID { get; set; }
        public string FUEL_NAME { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> DEPENDABLE_CAPACITY { get; set; }
        public string INV_METHOD_CODE { get; set; }
        public Nullable<decimal> ESTIMATED_CONSUMPTION { get; set; }
        public Nullable<decimal> EMO_PERIOD_ID { get; set; }
        public Nullable<System.DateTime> FORECAST_FROM_DATE { get; set; }
        public Nullable<System.DateTime> FORECAST_TO_DATE { get; set; }
        public Nullable<System.DateTime> PORTAL_SUBMISSION_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<int> ORGANIZATION_ID { get; set; }
        public Nullable<decimal> REVISED_BY { get; set; }
        public Nullable<System.DateTime> REVISED_DATE_TIME { get; set; }
        public string REVISED_REASON { get; set; }
        public Nullable<decimal> OLD_FORECAST_HEADER_ID { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public Nullable<int> ERP_TRANSFER { get; set; }
    }
}
