//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_FC_OPN_STK_LINES
    {
        public decimal OPN_STOCK_LINE_ID { get; set; }
        public Nullable<decimal> FORECAST_HEADER_ID { get; set; }
        public string STOCK_DESCRIPTION { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    }
}
