//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_FUEL_TEMP_LINES
    {
        public decimal FUEL_TEMPLATE_LINE_ID { get; set; }
        public Nullable<decimal> FUEL_TEMPLATE_ID { get; set; }
        public string COMP_NAME { get; set; }
        public string COMP_TYPE { get; set; }
        public string COMP_VALUE { get; set; }
        public string FORMULA { get; set; }
        public string UNIT { get; set; }
        public string SHOW_ON_PORTAL { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<decimal> COMP_SEQUENCE { get; set; }
        public string COM_REF_CODE { get; set; }
        public Nullable<bool> SHOW_ON_ERP { get; set; }
    }
}
