//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_PERIODS
    {
        public decimal EMO_PERIOD_ID { get; set; }
        public string PERIOD_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string PERIOD_TYPE { get; set; }
        public Nullable<decimal> PERIOD_YEAR { get; set; }
        public Nullable<decimal> PERIOD_NUM { get; set; }
        public Nullable<decimal> QUARTER_NUM { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<decimal> ORGANIZATION_ID { get; set; }
        public Nullable<bool> OPEN_BY_CPPA { get; set; }
    }
}
