//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_EMO_FUEL_TEMP_HEADER
    {
        public decimal FUEL_TEMPLATE_ID { get; set; }
        public string FUEL_TEMPLATE_NAME { get; set; }
        public string FUEL_NAME { get; set; }
        public string POWER_POLICY { get; set; }
        public string SHOW_OPENING_STOCK { get; set; }
        public string STOCK_MEASURING_UNIT { get; set; }
        public string REMARKS { get; set; }
        public string ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    }
}
