//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPPA_PPA_SCH_10
    {
        public int SCH_10_ID { get; set; }
        public int VENDOR_ID { get; set; }
        public decimal HEADER_ID_PK { get; set; }
        public string FUEL_LOOKUP_CODE { get; set; }
        public string SCH_10_TYPE { get; set; }
        public string REMARKS { get; set; }
        public decimal CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
