//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FND_LOOKUP_VALUES
    {
        public decimal FND_LOOKUP_VALUES_ID_PK { get; set; }
        public string LOOKUP_TYPE { get; set; }
        public string LANGUAGE { get; set; }
        public string LOOKUP_CODE { get; set; }
        public string MEANING { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENABLED_FLAG { get; set; }
        public Nullable<System.DateTime> START_DATE_ACTIVE { get; set; }
        public Nullable<System.DateTime> END_DATE_ACTIVE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string SOURCE_LANG { get; set; }
        public Nullable<int> SECURITY_GROUP_ID { get; set; }
        public Nullable<int> VIEW_APPLICATION_ID { get; set; }
        public string TERRITORY_CODE { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public string TAG { get; set; }
        public string LEAF_NODE { get; set; }
        public string ZD_EDITION_NAME { get; set; }
    }
}
