//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDINEO_HEADER
    {
        public decimal HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<decimal> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public string DOC_MONTH { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public Nullable<decimal> MDI_TOTAL { get; set; }
        public Nullable<decimal> NEO_TOTAL { get; set; }
        public Nullable<int> FLAG { get; set; }
    }
}
