//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSEntities : DbContext
    {
        public DBSEntities()
            : base("name=DBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CPPA_PPA_SCH_10> CPPA_PPA_SCH_10 { get; set; }
        public virtual DbSet<CPPA_PPA_SCH_10_DTL> CPPA_PPA_SCH_10_DTL { get; set; }
    }
}
