//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantBlock
    {
        public decimal PLT_BLK_FUEL_ID { get; set; }
        public Nullable<decimal> HEADER_ID_FK { get; set; }
        public string BLOCK_UNIT_TITLE { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public string GROUP_COMP { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_SITE_CODE { get; set; }
        public string POWER_POLICY { get; set; }
        public int VENDOR_SITE_ID { get; set; }
        public int VENDOR_ID { get; set; }
    }
}
