//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFile
    {
        public decimal tblFilesID { get; set; }
        public string strFileName { get; set; }
        public string strSPUrl { get; set; }
        public string strDescription { get; set; }
        public Nullable<bool> bisERPTransfered { get; set; }
    }
}
