//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_DISCO_CDP_MONTHLY_DATA
    {
        public decimal WP_DISCO_CDP_MONTHLY_DATA_ID { get; set; }
        public Nullable<decimal> CDP_ID { get; set; }
        public Nullable<int> ACCOUNTING_MONTH_ID { get; set; }
        public Nullable<System.DateTime> PM_READING_DATE_TIME { get; set; }
        public string IS_PRIMARY_METER { get; set; }
        public Nullable<decimal> PRIMARY_CDP_DTL_ID { get; set; }
        public Nullable<decimal> BACKUP_CDP_DTL_ID { get; set; }
        public Nullable<decimal> PREVIOUS_WP_DISCO_CDP_MONTHLY_DATA_ID { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_ACTIVE_READING { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_REACTIVE_READING { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_ACTIVE_MDI { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_REACTIVE_MDI { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_ACTIVE_READING { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_REACTIVE_READING { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_ACTIVE_MDI { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_REACTIVE_MDI { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_ACTIVE_AJD { get; set; }
        public Nullable<decimal> PRIMARY_IMPORT_REACTIVE_ADJ { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_ACTIVE_AJD { get; set; }
        public Nullable<decimal> PRIMARY_EXPORT_REACTIVE_ADJ { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_ACTIVE_READING { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_REACTIVE_READING { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_ACTIVE_MDI { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_REACTIVE_MDI { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_ACTIVE_READING { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_REACTIVE_READING { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_ACTIVE_MDI { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_REACTIVE_MDI { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_ACTIVE_AJD { get; set; }
        public Nullable<decimal> BACKUP_IMPORT_REACTIVE_ADJ { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_ACTIVE_AJD { get; set; }
        public Nullable<decimal> BACKUP_EXPORT_REACTIVE_ADJ { get; set; }
        public Nullable<decimal> P_ENG_ACTIVE_IMPORT { get; set; }
        public Nullable<decimal> P_ENG_ACTIVE_EXPORT { get; set; }
        public Nullable<decimal> P_MDI_ACTIVE_IMPORT { get; set; }
        public Nullable<decimal> P_MDI_ACTIVE_EXPORT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> CREATED_BY_WP_PORTAL_USERS_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY_WP_PORTAL_USERS_ID { get; set; }
        public int Status { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> BM_READING_DATE_TIME { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public Nullable<decimal> B_ENG_ACTIVE_IMPORT { get; set; }
        public Nullable<decimal> B_ENG_ACTIVE_EXPORT { get; set; }
        public Nullable<decimal> B_MDI_ACTIVE_IMPORT { get; set; }
        public Nullable<decimal> B_MDI_ACTIVE_EXPORT { get; set; }
        public Nullable<System.DateTime> PM_PREVIOUS_READING_DATE_TIME { get; set; }
        public Nullable<System.DateTime> BM_PREVIOUS_READING_DATE_TIME { get; set; }
        public Nullable<decimal> PREVIOUS_READING_PRIM_IMP_ACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_PRIM_IMP_REACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_PRIM_EXP_ACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_PRIM_EXP_REACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_BACK_IMP_ACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_BACK_IMP_REACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_BACK_EXP_ACT { get; set; }
        public Nullable<decimal> PREVIOUS_READING_BACK_EXP_REACT { get; set; }
        public Nullable<System.DateTime> SUBMITT_DATE_TIME { get; set; }
        public Nullable<bool> CPPA_SELECTED { get; set; }
        public Nullable<bool> PM_ROUND_COMPLETED_IA { get; set; }
        public Nullable<bool> BM_ROUND_COMPLETED_IA { get; set; }
        public Nullable<bool> PM_ROUND_COMPLETED_IR { get; set; }
        public Nullable<bool> BM_ROUND_COMPLETED_IR { get; set; }
        public Nullable<bool> PM_ROUND_COMPLETED_EA { get; set; }
        public Nullable<bool> BM_ROUND_COMPLETED_EA { get; set; }
        public Nullable<bool> PM_ROUND_COMPLETED_ER { get; set; }
        public Nullable<bool> BM_ROUND_COMPLETED_ER { get; set; }
    }
}
