//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_FILES
    {
        public decimal WP_FILE_ID { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE_TIME { get; set; }
        public string FILE_URL { get; set; }
        public Nullable<decimal> PARENT_ID { get; set; }
        public string UPLOADED_FOR { get; set; }
        public string FILE_TITLE { get; set; }
        public string FILE_DESCRIPTION { get; set; }
        public Nullable<bool> ERP_TRANSFER { get; set; }
        public string SHAREPOINT_FILE_ID { get; set; }
        public string SHAREPOINT_FILE_GUID { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public string FILES_NAME { get; set; }
        public string FILE_EXT { get; set; }
        public string FILE_TYPE { get; set; }
        public string ONLINE_URL { get; set; }
    }
}
