//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_GC_HOURLY_DATA_HEADER
    {
        public decimal WP_GC_HOURLY_DATA_HEADER_ID_PK { get; set; }
        public Nullable<decimal> VENDOR_SITE_ID_FK { get; set; }
        public string HOURLY_DATA_TYPE { get; set; }
        public string GENERATION_COMPANY { get; set; }
        public Nullable<bool> COMPLEX_WISE { get; set; }
        public string SITE { get; set; }
        public string BLOCK { get; set; }
        public string FUEL { get; set; }
        public Nullable<System.DateTime> INTIMATION_DATE_TIME { get; set; }
        public Nullable<System.DateTime> TARGET_DATE { get; set; }
        public Nullable<bool> INTIMATION_SOURCE_TELEPHONE { get; set; }
        public Nullable<System.DateTime> INTIMATION_SOURCE_TELEPHONE_DATE_TIME { get; set; }
        public Nullable<bool> INTIMATION_SOURCE_FAX { get; set; }
        public Nullable<System.DateTime> INTIMATION_SOURCE_FAX_DATE_TIME { get; set; }
        public Nullable<bool> INTIMATION_SOURCE_PORTAL { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> ACK_TIME { get; set; }
        public string SENDER_NAME { get; set; }
        public string SENDER_DESIGNATION { get; set; }
        public string SENDER_REMARKS { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string RECEIVER_DESIGNATION { get; set; }
        public string RECEIVER_REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string POWER_POLICIY { get; set; }
        public Nullable<decimal> PLT_BLK_FUEL_ID { get; set; }
        public string IS_REVISED { get; set; }
        public Nullable<decimal> PARENT_ID { get; set; }
        public Nullable<decimal> CURRENT_AVAILABILITY { get; set; }
        public Nullable<decimal> REVISED_AVAILABILITY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string REVISION_TYPE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
    }
}
