//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_GC_USER_ACCESS
    {
        public long WP_GC_USER_ACCESS_ID { get; set; }
        public int WP_PORTAL_USERS_ID { get; set; }
        public Nullable<int> ENTITY_WP_SETUP_USER_TYPES { get; set; }
        public int ENTITY_ID { get; set; }
        public Nullable<int> ENTITY_SITE_ID { get; set; }
        public string ENTITY_TABLE_NAME { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE_TO { get; set; }
        public Nullable<bool> INQUIRY_RIGHTS { get; set; }
        public Nullable<bool> CREATE_RIGHTS { get; set; }
        public Nullable<bool> EDIT_RIGHTS { get; set; }
        public Nullable<bool> DELETE_RIGHTS { get; set; }
        public bool HISTORICAL_DATA_VIEW_RIGHTS { get; set; }
    }
}
