//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_NPCC_LOAD_CURTAILMENT
    {
        public decimal WP_NPCC_LOAD_CURTAILMENT_ID_PK { get; set; }
        public Nullable<decimal> GENERATION_COMPANY_ID_FK { get; set; }
        public string GENERATION_COMPANY { get; set; }
        public Nullable<double> TOTAL_WTG { get; set; }
        public Nullable<double> AVAILABLE_WTG { get; set; }
        public Nullable<double> UNAVAILABLE_DUE_TO_FO { get; set; }
        public Nullable<double> UNAVAILABLE_DUE_TO_SO { get; set; }
        public string INSTRUCTION_TYPE { get; set; }
        public Nullable<bool> WTG_CURTAILMENT { get; set; }
        public Nullable<bool> LOAD_CURTAILMENT { get; set; }
        public string CURTAILMENT_DETAIL { get; set; }
        public Nullable<System.DateTime> NOTIFICATION_TIME { get; set; }
        public Nullable<System.DateTime> SYNC_DYSYNC_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_ACHIEVEMENT_TIME { get; set; }
        public Nullable<double> PRIOR_TO_CURTAILMENT { get; set; }
        public Nullable<double> AFTER_CURTAILMENT { get; set; }
        public Nullable<double> WTG_PRIOR_TO_CURTAILMENT { get; set; }
        public Nullable<double> WTG_AFTER_CURTAILMENT { get; set; }
        public string SENDER_NAME { get; set; }
        public string SENDER_DESIGNATION { get; set; }
        public string NPCC_REMARKS { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string RECEIVER_DESIGNATION { get; set; }
        public string GC_REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string SITE { get; set; }
        public string STATUS { get; set; }
        public string ACH_REMARKS { get; set; }
        public Nullable<decimal> FLAG { get; set; }
    }
}
