//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_NPCC_DESPATCH_DETAIL
    {
        public decimal WP_NPCC_DESPATCH_DETAIL_ID { get; set; }
        public decimal WP_NPCC_DESPATCH_HEADER_ID { get; set; }
        public string BLOCK_ID { get; set; }
        public string BLOCK_NAME { get; set; }
        public Nullable<System.DateTime> SYNC_DESYNC_TIME { get; set; }
        public string REMARKS { get; set; }
    }
}
