//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_NPCC_METERING
    {
        public decimal WP_NPCC_METERING_ID { get; set; }
        public Nullable<System.DateTime> PLT_MTR_FROM_TIME { get; set; }
        public Nullable<System.DateTime> PLT_MTR_TO_TIME { get; set; }
        public string NEO_DELIVERED { get; set; }
        public Nullable<decimal> FLAG { get; set; }
    }
}
