//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_NPCC_HOURLY_DATA_SMRY_DETAIL
    {
        public decimal HOURLY_DATA_SUMMARY_DETAIL_ID_PK { get; set; }
        public Nullable<decimal> HOURLY_DATA_SUMMARY_HEADER_ID_FK { get; set; }
        public Nullable<int> RECORD_SEQUENCE { get; set; }
        public Nullable<System.DateTime> DATA_DATE { get; set; }
        public Nullable<System.TimeSpan> DATA_HOUR { get; set; }
        public string BOD_DAC_AVAILABILITY { get; set; }
        public string BOD_DAC_TEMP { get; set; }
        public Nullable<System.DateTime> BOD_DAC_INTIMATION_TIME { get; set; }
        public string BOD_RDAC_P12TO4_AVAILABILITY { get; set; }
        public string BOD_RDAC_P12TO4_TEMP { get; set; }
        public Nullable<System.DateTime> BOD_RDAC_P12TO4_INTIMATION_TIME { get; set; }
        public string BOD_RDAC_P4TO0_AVAILABILITY { get; set; }
        public string BOD_RDAC_P4TO0_TEMP { get; set; }
        public Nullable<System.DateTime> BOD_RDAC_P4TO0_INTIMATION_TIME { get; set; }
        public string BOD_FINALDAC { get; set; }
        public string OD_UPWARDREVISION_4HOURS_AVAILABILITY { get; set; }
        public string OD_UPWARDREVISION_4HOURS_INTIMATION_TIME { get; set; }
        public string OD_REVISION_1HOUR_AVAILABILITY { get; set; }
        public string OD_REVISION_1HOUR_INTIMATION_TIME { get; set; }
        public string OD_ADAC_45MINUTES_AVAILABILITY { get; set; }
        public string OD_ADAC_45MINUTES_TEMP { get; set; }
        public string OD_ADAC_45MINUTES_INTIMATION_TIME { get; set; }
        public string OD_FINAL_DAC { get; set; }
        public string NPCC_DESPATCH_INSTRUCTION { get; set; }
        public string NPCC_DESPATCH_AS_PER_PPA { get; set; }
        public string NPCC_DESPATCH_WITH_EXCESS_LIMIT { get; set; }
        public string NEO_DELIVERED { get; set; }
        public string NEO_DELIVERED_FUEL1 { get; set; }
        public string NEO_DELIVERED_FUEL2 { get; set; }
        public string NEO_DELIVERED_FUEL3 { get; set; }
        public string NEO_DELIVERED_FUEL4 { get; set; }
        public string ADMISSIBLE_NEO { get; set; }
        public string ADMISSIBLE_NEO_FUEL1 { get; set; }
        public string ADMISSIBLE_NEO_FUEL2 { get; set; }
        public string ADMISSIBLE_NEO_FUEL3 { get; set; }
        public string ADMISSIBLE_NEO_FUEL4 { get; set; }
        public string SCHEDULED_OUTAGE { get; set; }
        public string FORCED_OUTAGE { get; set; }
        public string APPLICABLE_WIND_FACTOR { get; set; }
        public string ADMISSIBLE_CAPACITY { get; set; }
        public string REMARKS { get; set; }
    }
}
