//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_SETUP_MENU
    {
        public int WP_SETUP_MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string Herf_LINK { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> ORDER_BY { get; set; }
        public string CONTROLLER { get; set; }
        public string CONTROLLER_VIEW { get; set; }
        public Nullable<bool> IS_VIEW_PARTIAL { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
