//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_SETUP_DISCO
    {
        public decimal WP_SETUP_DISCO_ID { get; set; }
        public Nullable<decimal> CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<decimal> CUSTOMER_NUMBER { get; set; }
        public string ABBREVIATION { get; set; }
    }
}
