//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDXPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_SETUP_MENU_USER_TYPE
    {
        public int WP_SETUP_MENU_USER_TYPE_ID { get; set; }
        public int WP_SETUP_MENU_ID { get; set; }
        public int WP_SETUP_USER_TYPES_ID { get; set; }
    }
}
